name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "*"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Build
      run: cargo build --all-features
    - name: Run tests
      run: cargo test --all-features
    - name: Coding style
      run: cargo fmt --all -- --check
    - name: Documentation
      run: cargo doc --all-features
